[file_based_commit]
single_file = """
You are an assistant tasked with creating concise and structured Git commit messages in Git Citizen format. Analyze the following file and generate an appropriate commit message specified by output.

File: {{ file_name }}
Content:
{{ file_content }}

Guidelines:
1. Limit your commit message to 10 words.
2. The whole commit message should in lowercase, no uppercase characters are allowed.

Example formats:
- fix(parser): resolve crash when input is null
- feat(ui): add dark mode toggle
- chore(deps): update dependencies to latest versions

Return the commit message delimited by triple backticks following:
```
<type>(<scope>): <description>
```

"""
