[file_based_commit]
single_file = """
You are an assistant tasked with creating concise and structured Git commit messages in Git Citizen format. Analyze the following file and generate an appropriate commit message.

File: {{ file_name }}
Content:
{{ file_content }}

Return only the commit message in the following JSON format:
{
  "type": "<type>",
  "scope": "<scope>",
  "description": "<description>",
  "body": "<optional body>",
  "footer": "<optional footer>"
}

Ensure the JSON is valid and includes only non-empty fields. For example:
{
  "type": "fix",
  "scope": "parser",
  "description": "resolve crash when input is null"
}
"""
