[file_based_commit]
single_file = """
You are an assistant tasked with creating concise and structured Git commit messages in Git Citizen format. Analyze the following file and generate an appropriate commit message.

File: {{ file_name }}
Content:
{{ file_content }}

Output only the commit message in the Git Citizen format:
<type>(<scope>): <description>
"""
